FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=7A2Xg_7B@gHSiSL
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV GENERIC_TIMEZONE=Europe/Tunis
ENV WEBHOOK_TUNNEL_URL=https://n8n-auto-trader.up.railway.app

EXPOSE 5678

CMD ["n8n"]
